- hosts: allvm
  tasks:

# imlib-1.9.13-1.el5.rf.x86_64.rpm
  - name: copy icewm necessary RPM to remote VM.(EL5,6,7.copy all.)
    copy: src=/root/suse/RPM/icewm/{{ item.filename }} dest=/tmp/ owner=root mode=600
    with_items:
    - filename: imlib-1.9.15-6.el5.x86_64.rpm
    - filename: icewm-1.3.7-7.el5.x86_64.rpm
    when:
      ansible_distribution_major_version|int == 5




  - name:  ensure icewm installed on EL5 nodes.
    yum: pkg=/tmp/{{item.filename}} state=installed disable_gpg_check=yes
    with_items: 
    - filename: imlib-1.9.15-6.el5.x86_64.rpm
    - filename: icewm-1.3.7-7.el5.x86_64.rpm
    when:
      ansible_distribution_major_version|int == 5
